# Generated by Django 6.0.4 on 2026-04-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_caption', models.CharField(max_length=255)),
                ('post_image', models.ImageField(upload_to='posts/')),
                ('post_creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
